services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=my_erp
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=admin_my_erp
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - my_erp_db:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  my_erp_db:

secrets:
  postgresql_password:
    file: ./my_erp_pass